//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beestje_eindopdracht.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beestjes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beestjes()
        {
            this.Accessoires = new HashSet<Accessoires>();
            this.Boeking = new HashSet<Boeking>();
        }
    
        public int Id { get; set; }
        public int BeestType_id { get; set; }
        public string Naam { get; set; }
        public string Prijs { get; set; }
        public string Afbeelding { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accessoires> Accessoires { get; set; }
        public virtual BeestType BeestType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boeking> Boeking { get; set; }
    }
}
