//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beestje_eindopdracht.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boeking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boeking()
        {
            this.Beestjes = new HashSet<Beestjes>();
        }
    
        public int Id { get; set; }
        public System.DateTime datum { get; set; }
        public string contact_naam { get; set; }
        public string contact_adres { get; set; }
        public string contact_email { get; set; }
        public string contact_telefoonnummer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beestjes> Beestjes { get; set; }
    }
}
