//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beestje_eindopdracht.Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class beestje_databaseEntities : DbContext
    {
        public beestje_databaseEntities()
            : base("name=beestje_databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessoires> Accessoires { get; set; }
        public virtual DbSet<Beestjes> Beestjes { get; set; }
        public virtual DbSet<BeestType> BeestType { get; set; }
        public virtual DbSet<Boeking> Boeking { get; set; }
    }
}
